# CI/CD Pipeline for Odoo Addons
#
# Reads configuration from pyproject.toml:
#   [odoo]
#   version = 17.0
#   build_docker = true    # Enable Docker build on deploy branches
#   fast_tests = true       # Enable unit tests (default: true)
#   edition = "enterprise"
#
# Flow:
#   PR: Quality Checks → Jenkins (Unit Tests only, if fast_tests=true)
#   Push to deploy branch: Quality Checks → Jenkins (Tests and/or Deploy based on flags)
#   Push to non-deploy branch: Quality Checks → Jenkins (Tests only, if fast_tests=true)

name: CI/CD

on:
  push:
    branches: [main, staging, production]  # Adjust to your branches
  pull_request:
    branches: [main, staging]              # PRs to these branches trigger CI
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  # ============================================
  # Stage 1: Quality Checks (GitHub Actions)
  # ============================================
  quality:
    uses: YOUR_ORG/github-actions/.github/workflows/odoo-quality.yml@main
    with:
      odoo-version: '17'      # Must match pyproject.toml [odoo] version
      python-version: '3.10'
      # skip-sonar: true      # Uncomment to skip SonarQube
      # strict-mode: true     # Uncomment to fail on quality issues
    secrets: inherit

  # ============================================
  # Stage 2: Unit Tests + Deploy (Jenkins)
  # ============================================
  # Reads pyproject.toml automatically for:
  #   - odoo version
  #   - fast_tests (true/false) - controls unit test execution
  #   - build_docker (true/false) - controls Docker build on deploy branches
  #   - edition (enterprise/community)
  #
  # Skips Jenkins entirely if both fast_tests=false AND build_docker=false
  jenkins:
    needs: quality
    uses: YOUR_ORG/github-actions/.github/workflows/jenkins-trigger.yml@main
    with:
      deploy-branches: 'main,production'  # Branches that trigger Docker deploy (comma-separated)
      # dry-run: true                     # Uncomment for testing without triggering Jenkins
    secrets: inherit
